### ISSUE TITLE
tdep_relax_cell.py help

### ISSUE THREAD

**Issue by DFT13** [flokno/tools.tdep#10]
Dear glokno, When running the tdep_relax_cell.py script, I meet the following error, can you give me some advices? How can I get A file?how do I get outfile.compliance_tensor file. Think you very much!
![2ff261ed0b31283b1c5666e5fa9728c](https://github.com/flokno/tools.tdep/assets/69805655/3e3efe72-0b73-4e29-9d5a-7785716c92e5)

**Comment by flokno** [comment]
Hi, this is an experimental feature that requires extra input. It is currently not supported for general use, sorry

**Comment by DFT13** [comment]
Thank you very much!
