### ISSUE TITLE
Parsing OUTCAR from an incomplete vasp run

### ISSUE THREAD

**Issue by akentphonon** [flokno/tools.tdep#5]
Dear @flokno ,

Thank you for these amazing set of tools. I have one query - when I try to parse an OUTCAR file from a long incomplete AIMD run into "tdep_read_outcar" if the vasp run is not complete it gives an error

 TIMINGS NOT FOUND, OUTPUT FILE BROKEN?

The issue is that vasp runs does not finish cleanly due to walltime limit of my super computers :(.  Say if I am requesting 5000 steps it has info about only 4000 steps, however the info from OUTCAR is still useful to continue with the TDEP simulations.

I was wondering if it was possible to enable parsing of incomplete OUTCAR files in tdep_read_outcar. This is similar to the behavior of the tdep script process_outcar_5.3.py.

Thanks for your time and contributions to open source.

Best,
Alex

**Comment by akentphonon** [comment]
My bad - I should be using tdep_parse_output.  I will close this.

**Comment by flokno** [comment]
Hi @akentphonon , thanks for pointing this out. I think `tdep_read_outcar` is outdated as you say, but then it should be removed from the scripts. Let’s keep this open for now

**Comment by flokno** [comment]
@akentphonon I updated the script name to reflect that its purpose was to parse out the `lotosplitting` file at this point. As you already noticed the script to parse our everything is `tdep_parse_output`. Thanks for reporting and happy computing!
