### ISSUE TITLE
Header of Born effective charges in VASP 5.4

### ISSUE THREAD

**Issue by sebasdav** [flokno/tools.tdep#8]
Hi. The header of the BORN effective charges in VASP 5.4 (old) is a bit different: "BORN EFFECTIVE CHARGES (in e, cummulative output)". The extraction of the lotosplitting file fails because of this. I just changed it to "BORN EFFECTIVE CHARGES (i" for both versions 5 and 6. In case you would like to update it.

https://github.com/flokno/tools.tdep/blob/531cf1f579927826dae8519a6506670cd21de174/tdeptools/scripts/tdep_read_lotosplitting_from_outcar.py#L8C1-L8C70

**Comment by flokno** [comment]
thanks! fixed in 7d81ed571442291d30478f620994543de2b35c5d
